[versions]
kotlin = "2.1.0"
ktor = "3.0.3"
coroutines = "1.10.1"

[libraries.kotlin-gradle]
version.ref = "kotlin"
module = "org.jetbrains.kotlin:kotlin-gradle-plugin"

[libraries.kotlin-coroutines-core]
version.ref = "coroutines"
module = "org.jetbrains.kotlinx:kotlinx-coroutines-core"

[libraries.kotlin-serialization-gradle]
version.ref = "kotlin"
module = "org.jetbrains.kotlin:kotlin-serialization"

[libraries.ktor-client-core]
version.ref = "ktor"
module="io.ktor:ktor-client-core"

[libraries.ktor-client-serialization]
version.ref = "ktor"
module="io.ktor:ktor-client-serialization"

[libraries.ktor-client-contentnegotiation]
version.ref = "ktor"
module="io.ktor:ktor-client-content-negotiation"

[libraries.ktor-serialization-json]
version.ref = "ktor"
module = "io.ktor:ktor-serialization-kotlinx-json"

[libraries.ktor-client-cio]
version.ref = "ktor"
module="io.ktor:ktor-client-cio"

[libraries.spondee-units]
version = "1.5.0"
module = "com.inkapplications.spondee:units"

[libraries.slf4j-shutthefuckup]
version = "2.0.13"
module = "org.slf4j:slf4j-nop"

[bundles]
cli = [
    "slf4j-shutthefuckup",
]
ktor-client = [
    "ktor-client-core",
    "ktor-client-serialization",
    "ktor-client-contentnegotiation",
    "ktor-serialization-json",
    "ktor-client-cio",
]
