[versions]
kotlin = "2.1.0"
ktor = "3.0.3"
coroutines = "1.10.1"

[libraries.kotlin-gradle]
version.ref = "kotlin"
module = "org.jetbrains.kotlin:kotlin-gradle-plugin"

[libraries.kotlin-coroutines-core]
version.ref = "coroutines"
module = "org.jetbrains.kotlinx:kotlinx-coroutines-core"

[libraries.kotlin-serialization-gradle]
version.ref = "kotlin"
module = "org.jetbrains.kotlin:kotlin-serialization"

[libraries.ktor-client-core]
version.ref = "ktor"
module="io.ktor:ktor-client-core"

[libraries.ktor-client-serialization]
version.ref = "ktor"
module="io.ktor:ktor-client-serialization"

[bundles]
ktor-client = [
    "ktor-client-core",
    "ktor-client-serialization",
]
