#!/usr/bin/env bash

set -euo pipefail;

# Resolve project root
SOURCE="${BASH_SOURCE[0]}";
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )";
  SOURCE="$(readlink "$SOURCE")";
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
PROJECT_ROOT="$( cd -P "$( dirname "$SOURCE" )/../../.." >/dev/null 2>&1 && pwd )";

relink() {
    local target="$1";
    local destination="$2";

    if [ -L "$destination" ]; then
        echo "Removing existing symlink at: $destination";
        rm -v "$destination"
    elif [ -f "$destination" ]; then
        echo "Archiving existing file at: $destination";
        local timestamp=$(date +"%Y%m%d%H%M%S");
        local archive="$(dirname "$destination")"/.archive-"$timestamp"."$(basename "$destination")";
        mv -v "$destination" "$archive"
    elif [ -e "$destination" ]; then
        echo "Unexpected file type at $destination";
        return 1;
    fi

    ln -sv -- "$target" "$destination";
}

echo "Linking Bash Config";
relink "$PROJECT_ROOT/src/main/bash/profiles/main.bash_profile" "$HOME/.bash_profile"
source "$HOME/.bash_profile"

echo "Linking Ghostty Config";
relink "$PROJECT_ROOT/src/main/resources/configs/ghostty.properties" "$HOME/.config/ghostty/config"

echo "Linking Git Configs";
relink "$PROJECT_ROOT/src/main/resources/configs/global.gitconfig" "$HOME/.gitconfig"
relink "$PROJECT_ROOT/src/main/resources/configs/global.gitignore" "$HOME/.gitignore"

BASH_LINK_DEFAULT="$(which bash)"
BASH_LINK="$HOME/.local/bin/bash"
if [ ! -f "$BASH_LINK" ]; then
    read -p "local bash target not found ($BASH_LINK). Set path ($BASH_LINK_DEFAULT): " BASH_TARGET;
    BASH_TARGET="${BASH_TARGET:-$BASH_LINK_DEFAULT}"
fi
relink "BASH_TARGET" "$BASH_LINK"
