#!/usr/bin/env bash

title() {
    title="${PWD##*/}"
    echo "$title"
    echo "${title//?/=}"
}

gitinfo() {
    if [ -d ".git" ]; then
        echo
        echo "Git Info"
        echo "--------"
        echo "Branches:"
        git branch
        echo
        echo "Remotes:"
        git remote -v

        if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
            echo
            echo "Changes:"
            added=0
            removed=0
            modified=0
            untracked=0
            while read -r line; do
                case "$line" in
                    A*) added=$((added + 1)) ;;
                    D*) removed=$((removed + 1)) ;;
                    M*) modified=$((modified + 1)) ;;
                esac
            done < <(git status --porcelain)
            untracked=$(git status --porcelain | grep '^??' | wc -l)

            printf "Added: %d, Removed: %d, Modified: %d, Untracked: %d\n" "$added" "$removed" "$modified" "$untracked"
        fi
    fi
}

executables() {
    executables=$(find ./bin ./project-bin -type f -perm -u+x 2>/dev/null)

    if [ ! -z "$executables" ]; then
        echo
        echo "Local Commands"
        echo "--------------"
        echo "$executables" | awk -F/ '{print " - " $NF}'
    fi
}

main() {
    clear
    title
    pwd
    gitinfo
    executables
}

main "$@"
